### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by radiofreejohn**

### CODE REVIEW

**Comment by radiofreejohn** [comment]
ugh, I did it again! :)

With that said, I think I'm finished, have a look and let me know if/what you might want to pull in.

**Comment by hstove** [comment]
Hey, your changes look great. What I'd like to do is unify our projects so that there aren't two `electron-cookies` packages out there to confuse people. If Heap is down to maintain the project, I'm happy to pass the reigns to your team. That would mean:

- adding a note in this Github project to point folks to the heap repo
- adding heap team members as contributors on NPM, so you can push updates
- adding me as a contributor to the Heap project

You down?

**Comment by radiofreejohn** [comment]
@hstove yeah, where should I start :)

**Comment by hstove** [comment]
@radiofreejohn send me an email and we'll finish things out. My email is public on my Github profile page. I just added a note in this project's README to send folks to your repo

**Pull request closed without merging**
